import { Dialog, InfoBlock, CompletionSummary } from '../shared';
import { personas } from '../personas';
import { compactText } from '../OfficeFloor';
import type { Task } from '../api';

export function TaskModal({ task, brief, completedRunIds, mainAction, busy, controlTask, beginPlannedExecution, workspace, onOpenRequest, onOpenChat, onOpenEvidence, onOpenReflection, onClose }: {
  task: Task | null; brief: string; completedRunIds: Set<string>; mainAction: { label: string; action: () => void };
  busy: string; controlTask: (action: 'pause' | 'resume' | 'cancel') => void; beginPlannedExecution: () => void;
  workspace: unknown; onOpenRequest: () => void; onOpenChat: () => void; onOpenEvidence: () => void; onOpenReflection: () => void; onClose: () => void;
}) {
  return <Dialog title="CEO 브리핑" onClose={onClose}>
    <p className="dialog-copy">{task?.state === 'completed' ? '요청한 작업이 완료되었습니다. 결과를 확인하고 다음 행동을 선택하세요.' : brief || (task ? `${task.title} · ${task.state_label} · 실제 실행 ${completedRunIds.size}건` : 'NAVI가 새 업무를 기다리고 있습니다.')}</p>
    <div className="brief-primary-actions"><button className="solid-button" onClick={onOpenRequest}>+ 새 업무 / 대화</button><button className="text-button" onClick={onOpenChat} disabled={!task}>이 업무와 대화하기</button><button className="text-button" onClick={onOpenEvidence} disabled={!task}>{task?.state === 'completed' ? '자세히 보기' : '실행 근거 보기'}</button></div>
    {task && <section className="brief-live"><div><small>현재 Job</small><b>{task.jobs.find(job => ['running', 'queued', 'pause_requested', 'cancel_requested'].includes(job.state)) ? `${task.jobs.find(job => ['running', 'queued', 'pause_requested', 'cancel_requested'].includes(job.state))?.kind} · ${task.jobs.find(job => ['running', 'queued', 'pause_requested', 'cancel_requested'].includes(job.state))?.state}` : '없음'}</b></div><div><small>다음 행동</small><b>{mainAction.label}</b></div><div><small>최근 실제 이벤트</small><b>{task.job_events[0] ? `${task.job_events[0].type} · ${task.job_events[0].summary}` : '아직 실제 이벤트 없음'}</b></div></section>}
    {task?.state === 'completed' ? <CompletionSummary task={task} onDetails={onOpenEvidence} /> : task && <><InfoBlock label="현재 업무" value={task.title} />{task.execution_plan && <><InfoBlock label="AI 실행 판단" value={task.execution_plan.plan.summary} /><InfoBlock label="부서 인계 흐름" value={task.execution_plan.plan.phases.map(phase => `${personas[phase.lead_id]?.name ?? phase.lead_id}: ${compactText(phase.objective, 100)} → ${phase.handoff_to ? personas[phase.handoff_to]?.name ?? phase.handoff_to : '최종 산출물'}`).join('\n')} /></>}<InfoBlock label="담당 팀" value={task.assigned_employees.map(id => personas[id]?.name ?? id).join(' · ')} /><InfoBlock label="모델 예산" value={`${task.budget_spent.toLocaleString()} / ${(task.contract?.token_limit ?? 0).toLocaleString()} tokens`} /><div className="decision-row">{task.state === 'paused' ? <button className="solid-button" onClick={() => controlTask('resume')} disabled={Boolean(busy)}>재개</button> : <button className="text-button" onClick={() => controlTask('pause')} disabled={Boolean(busy) || ['completed', 'cancelled'].includes(task.state)}>일시 정지</button>}<button className="danger-button" onClick={() => controlTask('cancel')} disabled={Boolean(busy) || ['completed', 'cancelled'].includes(task.state)}>업무 취소</button></div>{task.state === 'planning' && !workspace && <button className="solid-button wide" onClick={beginPlannedExecution} disabled={Boolean(busy)}>계획을 실행 단계로 전환</button>}<button className="text-button" onClick={onOpenEvidence}>산출물·근거 상세 보기 →</button><button className="text-button" onClick={onOpenReflection}>회고와 회사 기억 →</button></>}
  </Dialog>;
}
